# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir W:/ECE532/New1/project_1_1/project_1/vivado/vivado.cache/wt [current_project]
set_property parent.project_path W:/ECE532/New1/project_1_1/project_1/vivado/vivado.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths {
  w:/ECE532/New1/project_1_1/project_1/ip_repo/comm_1.0
  w:/ECE532/New1/project_1_1/project_1/vga_ip/vga_ip.srcs/sources_1/imports/ECE532
  w:/ECE532/New1/project_1_1/project_1/video_in/video_in.srcs/sources_1/new
  w:/ECE532/New1/project_1_1/project_1/ipu/ipu.srcs/sources_1
} [current_project]
add_files W:/ECE532/New1/project_1_1/project_1/vivado/vivado.srcs/sources_1/bd/design_1/design_1.bd
set_property used_in_implementation false [get_files -all w:/ECE532/New1/project_1_1/project_1/vivado/vivado.srcs/sources_1/bd/design_1/ip/design_1_v_vid_in_axi4s_0_0/design_1_v_vid_in_axi4s_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all w:/ECE532/New1/project_1_1/project_1/vivado/vivado.srcs/sources_1/bd/design_1/ip/design_1_v_vid_in_axi4s_0_0/design_1_v_vid_in_axi4s_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all w:/ECE532/New1/project_1_1/project_1/vivado/vivado.srcs/sources_1/bd/design_1/ip/design_1_blk_mem_gen_0_0/design_1_blk_mem_gen_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all w:/ECE532/New1/project_1_1/project_1/vivado/vivado.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all w:/ECE532/New1/project_1_1/project_1/vivado/vivado.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all w:/ECE532/New1/project_1_1/project_1/vivado/vivado.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all w:/ECE532/New1/project_1_1/project_1/vivado/vivado.srcs/sources_1/bd/design_1/ip/design_1_microblaze_0_0/design_1_microblaze_0_0.xdc]
set_property used_in_implementation false [get_files -all w:/ECE532/New1/project_1_1/project_1/vivado/vivado.srcs/sources_1/bd/design_1/ip/design_1_microblaze_0_0/design_1_microblaze_0_0_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all w:/ECE532/New1/project_1_1/project_1/vivado/vivado.srcs/sources_1/bd/design_1/ip/design_1_microblaze_0_0/design_1_microblaze_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all w:/ECE532/New1/project_1_1/project_1/vivado/vivado.srcs/sources_1/bd/design_1/ip/design_1_dlmb_v10_0/design_1_dlmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all w:/ECE532/New1/project_1_1/project_1/vivado/vivado.srcs/sources_1/bd/design_1/ip/design_1_dlmb_v10_0/design_1_dlmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all w:/ECE532/New1/project_1_1/project_1/vivado/vivado.srcs/sources_1/bd/design_1/ip/design_1_ilmb_v10_0/design_1_ilmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all w:/ECE532/New1/project_1_1/project_1/vivado/vivado.srcs/sources_1/bd/design_1/ip/design_1_ilmb_v10_0/design_1_ilmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all w:/ECE532/New1/project_1_1/project_1/vivado/vivado.srcs/sources_1/bd/design_1/ip/design_1_dlmb_bram_if_cntlr_0/design_1_dlmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all w:/ECE532/New1/project_1_1/project_1/vivado/vivado.srcs/sources_1/bd/design_1/ip/design_1_ilmb_bram_if_cntlr_0/design_1_ilmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all w:/ECE532/New1/project_1_1/project_1/vivado/vivado.srcs/sources_1/bd/design_1/ip/design_1_lmb_bram_0/design_1_lmb_bram_0_ooc.xdc]
set_property used_in_implementation false [get_files -all w:/ECE532/New1/project_1_1/project_1/vivado/vivado.srcs/sources_1/bd/design_1/ip/design_1_microblaze_0_axi_intc_0/design_1_microblaze_0_axi_intc_0.xdc]
set_property used_in_implementation false [get_files -all w:/ECE532/New1/project_1_1/project_1/vivado/vivado.srcs/sources_1/bd/design_1/ip/design_1_microblaze_0_axi_intc_0/design_1_microblaze_0_axi_intc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all w:/ECE532/New1/project_1_1/project_1/vivado/vivado.srcs/sources_1/bd/design_1/ip/design_1_microblaze_0_axi_intc_0/design_1_microblaze_0_axi_intc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all w:/ECE532/New1/project_1_1/project_1/vivado/vivado.srcs/sources_1/bd/design_1/ip/design_1_mdm_1_0/design_1_mdm_1_0.xdc]
set_property used_in_implementation false [get_files -all w:/ECE532/New1/project_1_1/project_1/vivado/vivado.srcs/sources_1/bd/design_1/ip/design_1_mdm_1_0/design_1_mdm_1_0_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all w:/ECE532/New1/project_1_1/project_1/vivado/vivado.srcs/sources_1/bd/design_1/ip/design_1_rst_clk_wiz_0_50M_0/design_1_rst_clk_wiz_0_50M_0_board.xdc]
set_property used_in_implementation false [get_files -all w:/ECE532/New1/project_1_1/project_1/vivado/vivado.srcs/sources_1/bd/design_1/ip/design_1_rst_clk_wiz_0_50M_0/design_1_rst_clk_wiz_0_50M_0.xdc]
set_property used_in_implementation false [get_files -all w:/ECE532/New1/project_1_1/project_1/vivado/vivado.srcs/sources_1/bd/design_1/ip/design_1_rst_clk_wiz_0_50M_0/design_1_rst_clk_wiz_0_50M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all w:/ECE532/New1/project_1_1/project_1/vivado/vivado.srcs/sources_1/bd/design_1/ip/design_1_axi_uartlite_0_0/design_1_axi_uartlite_0_0_board.xdc]
set_property used_in_implementation false [get_files -all w:/ECE532/New1/project_1_1/project_1/vivado/vivado.srcs/sources_1/bd/design_1/ip/design_1_axi_uartlite_0_0/design_1_axi_uartlite_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all w:/ECE532/New1/project_1_1/project_1/vivado/vivado.srcs/sources_1/bd/design_1/ip/design_1_axi_uartlite_0_0/design_1_axi_uartlite_0_0.xdc]
set_property used_in_implementation false [get_files -all w:/ECE532/New1/project_1_1/project_1/vivado/vivado.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/design_1_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all w:/ECE532/New1/project_1_1/project_1/vivado/vivado.srcs/sources_1/bd/design_1/ip/design_1_axi_bram_ctrl_0_0/design_1_axi_bram_ctrl_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all w:/ECE532/New1/project_1_1/project_1/vivado/vivado.srcs/sources_1/bd/design_1/ip/design_1_blk_mem_gen_1_0/design_1_blk_mem_gen_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all w:/ECE532/New1/project_1_1/project_1/vivado/vivado.srcs/sources_1/bd/design_1/ip/design_1_auto_ds_0/design_1_auto_ds_0_ooc.xdc]
set_property used_in_implementation false [get_files -all w:/ECE532/New1/project_1_1/project_1/vivado/vivado.srcs/sources_1/bd/design_1/ip/design_1_auto_ds_0/design_1_auto_ds_0_clocks.xdc]
set_property used_in_implementation false [get_files -all w:/ECE532/New1/project_1_1/project_1/vivado/vivado.srcs/sources_1/bd/design_1/ip/design_1_auto_ds_1/design_1_auto_ds_1_ooc.xdc]
set_property used_in_implementation false [get_files -all w:/ECE532/New1/project_1_1/project_1/vivado/vivado.srcs/sources_1/bd/design_1/ip/design_1_auto_ds_1/design_1_auto_ds_1_clocks.xdc]
set_property used_in_implementation false [get_files -all w:/ECE532/New1/project_1_1/project_1/vivado/vivado.srcs/sources_1/bd/design_1/ip/design_1_auto_ds_2/design_1_auto_ds_2_ooc.xdc]
set_property used_in_implementation false [get_files -all w:/ECE532/New1/project_1_1/project_1/vivado/vivado.srcs/sources_1/bd/design_1/ip/design_1_auto_ds_2/design_1_auto_ds_2_clocks.xdc]
set_property used_in_implementation false [get_files -all w:/ECE532/New1/project_1_1/project_1/vivado/vivado.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all w:/ECE532/New1/project_1_1/project_1/vivado/vivado.srcs/sources_1/bd/design_1/ip/design_1_auto_us_0/design_1_auto_us_0_ooc.xdc]
set_property used_in_implementation false [get_files -all w:/ECE532/New1/project_1_1/project_1/vivado/vivado.srcs/sources_1/bd/design_1/ip/design_1_auto_us_0/design_1_auto_us_0_clocks.xdc]
set_property used_in_implementation false [get_files -all W:/ECE532/New1/project_1_1/project_1/vivado/vivado.srcs/sources_1/bd/design_1/design_1_ooc.xdc]
set_property is_locked true [get_files W:/ECE532/New1/project_1_1/project_1/vivado/vivado.srcs/sources_1/bd/design_1/design_1.bd]

read_verilog -library xil_defaultlib W:/ECE532/New1/project_1_1/project_1/vivado/vivado.srcs/sources_1/bd/design_1/hdl/design_1_wrapper.v
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc W:/ECE532/New1/project_1_1/project_1/vivado/vivado.srcs/constrs_1/new/constr.xdc
set_property used_in_implementation false [get_files W:/ECE532/New1/project_1_1/project_1/vivado/vivado.srcs/constrs_1/new/constr.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top design_1_wrapper -part xc7a100tcsg324-1


write_checkpoint -force -noxdef design_1_wrapper.dcp

catch { report_utilization -file design_1_wrapper_utilization_synth.rpt -pb design_1_wrapper_utilization_synth.pb }
